site_name: Material Plane Documentation
site_url: https://example.com
nav:
  - Home: index.md
  - Production Hardware: 
    - Getting Started: Production/gettingStarted.md
    - Requirements: Production/requirements.md
    - Hardware Overview: 
      - Sensor: Production/HardwareOverview/sensor.md
      - Bases: Production/HardwareOverview/bases.md
      - Pen: Production/HardwareOverview/pen.md
      - Dock & Dock Expansions: Production/HardwareOverview/dock.md
      - Base Adapters: Production/HardwareOverview/baseAdapters.md
    - Updating Firmware:
      - Sensor Updating: Production/Updating/sensorUpdating.md
      - Base & Pen Updating: Production/Updating/basePenUpdating.md
    - Sensor Positioning: 
      - Mounting: Production/SensorPositioning/sensorMounting.md
      - Sensor-to-Display Distance: Production/SensorPositioning/sensorDistance.md
      - Sensor Orientation: Production/SensorPositioning/sensorOrientation.md
    - Sensor Configuration: 
      - Connecting to WiFi: Production/SensorConfiguration/sensorConnecting.md
      - Webserver: Production/SensorConfiguration/webserver.md
      - Sensor Settings: Production/SensorConfiguration/sensorSettings.md
      - Wide-Angle Lens Installation: Production/SensorConfiguration/sensorLens.md
    - Base & Pen Configuration: Production/basePenConfig.md
    - VTT Configuration:
      - Foundry VTT:
        - Installing the Module: Shared/foundryInstall.md
        - Foundry Setup: Shared/foundrySetup.md
        - Connecting to the Sensor: Shared/foundryConnection.md
        - Module Configuration: Production/foundryConfig.md
    - Sensor Calibration: Production/calibration.md
    - Usage: 
      - Bases: Production/Usage/bases.md
      - Pen: Production/Usage/pen.md
  - Touch:
    - Touch: Touch/touch.md
    - Requirements: Touch/requirements.md
    - Getting Started: Touch/gettingStarted.md
    - Foundry Configuration: Touch/foundryConfig.md
    - Usage: Touch/usage.md
  - Display Selection: displaySelection.md
  - Hardware Comparison: hardwareComparison.md
  - FAQ: faq.md
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    
  features:
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - navigation.top
plugins:
  - search
  - macros:
      include_dir: include
markdown_extensions:
  - attr_list
extra_css: []